using Content.Client.Message;
using Content.Shared.DNA;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Content.Client.DNA;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.DNA.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class DNAConsoleWindow : FancyWindow
    {
        public DNAConsoleWindow()
        {
            
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
        }

        private DNAConsoleBoundUserInterfaceState? _lastUpdate;

        public void Populate(DNAConsoleBoundUserInterfaceState state)
        {
            _lastUpdate = state;
            // BUILD SCANNER UI
         
        }
    }
}
